"""Canonical NH town -> county mapping.

Seeded from 2012/code/county.pkl (259 towns, 10 counties). NH town boundaries
and county assignments are stable; this should only need maintenance when a
new town is incorporated or annexes between counties (rare).
"""

from __future__ import annotations

import re


_WARD_OR_DISTRICT_SUFFIX = re.compile(
    r"\s+-?\s*(?:Ward|Wd|Ward No\.?|District|Dist\.?)\s+\w+\s*\Z",
    re.IGNORECASE,
)


# Aliases for unincorporated townships / abbreviations the SoS uses that
# don't match the form recorded in TOWN_TO_COUNTY. Targets must already be
# keys in TOWN_TO_COUNTY (otherwise the lookup still returns None). The
# 2012-era map uses abbreviated canonical forms ("At. & Gil. Academy Grant")
# rather than the official long form; this map normalizes 2024 SoS variants
# to those existing keys.
PRECINCT_ALIASES: dict[str, str] = {
    "At. & Gil Ac. Gt": "At. & Gil. Academy Grant",
    "Atkinson & Gilmanton Academy Gt": "At. & Gil. Academy Grant",
    "Thomp. and Mes's Pur.": "Thompson & Meserve's Pur.",
    "Thompson & Meserve's Purchase": "Thompson & Meserve's Pur.",
}


def county_for_precinct(precinct: str) -> str | None:
    """Return the county for a precinct, handling ward/district suffixes and aliases.

    `'Concord Ward 1'` -> `'Merrimack'`. `'Dover - Ward 3'` -> `'Strafford'`.
    `'At. & Gil Ac. Gt'` -> `'Coos'` via PRECINCT_ALIASES.

    Returns None for unknown precincts. Callers decide what to do with that
    (e.g. emit a warning, leave county empty).
    """
    if precinct in TOWN_TO_COUNTY:
        return TOWN_TO_COUNTY[precinct]
    if precinct in PRECINCT_ALIASES:
        return TOWN_TO_COUNTY.get(PRECINCT_ALIASES[precinct])
    stripped = _WARD_OR_DISTRICT_SUFFIX.sub("", precinct).strip()
    if stripped and stripped != precinct:
        if stripped in TOWN_TO_COUNTY:
            return TOWN_TO_COUNTY[stripped]
        if stripped in PRECINCT_ALIASES:
            return TOWN_TO_COUNTY.get(PRECINCT_ALIASES[stripped])
    return None


TOWN_TO_COUNTY: dict[str, str] = {
    'Acworth': 'Sullivan',
    'Albany': 'Carroll',
    'Alexandria': 'Grafton',
    'Allenstown': 'Merrimack',
    'Alstead': 'Cheshire',
    'Alton': 'Belknap',
    'Amherst': 'Hillsborough',
    'Andover': 'Merrimack',
    'Antrim': 'Hillsborough',
    'Ashland': 'Grafton',
    'At. & Gil. Academy Grant': 'Coos',
    'Atkinson': 'Rockingham',
    'Auburn': 'Rockingham',
    'Barnstead': 'Belknap',
    'Barrington': 'Strafford',
    'Bartlett': 'Carroll',
    'Bath': 'Grafton',
    "Bean's Grant": 'Coos',
    "Bean's Purchase": 'Coos',
    'Bedford': 'Hillsborough',
    'Belmont': 'Belknap',
    'Bennington': 'Hillsborough',
    'Benton': 'Grafton',
    'Berlin': 'Coos',
    'Bethlehem': 'Grafton',
    'Boscawen': 'Merrimack',
    'Bow': 'Merrimack',
    'Bradford': 'Merrimack',
    'Brentwood': 'Rockingham',
    'Bridgewater': 'Grafton',
    'Bristol': 'Grafton',
    'Brookfield': 'Carroll',
    'Brookline': 'Hillsborough',
    'Cambridge': 'Coos',
    'Campton': 'Grafton',
    'Canaan': 'Grafton',
    'Candia': 'Rockingham',
    'Canterbury': 'Merrimack',
    'Carroll': 'Coos',
    'Center Harbor': 'Belknap',
    "Chandler's Purchase": 'Coos',
    'Charlestown': 'Sullivan',
    'Chatham': 'Carroll',
    'Chester': 'Rockingham',
    'Chesterfield': 'Cheshire',
    'Chichester': 'Merrimack',
    'Claremont': 'Sullivan',
    'Clarksville': 'Coos',
    'Colebrook': 'Coos',
    'Columbia': 'Coos',
    'Concord': 'Merrimack',
    'Conway': 'Carroll',
    'Cornish': 'Sullivan',
    "Crawford's Purchase": 'Coos',
    'Croydon': 'Sullivan',
    "Cutt's Grant": 'Coos',
    'Dalton': 'Coos',
    'Danbury': 'Merrimack',
    'Danville': 'Rockingham',
    'Deerfield': 'Rockingham',
    'Deering': 'Hillsborough',
    'Derry': 'Rockingham',
    "Dix's Grant": 'Coos',
    'Dixville': 'Coos',
    'Dorchester': 'Grafton',
    'Dover': 'Strafford',
    'Dublin': 'Cheshire',
    'Dummer': 'Coos',
    'Dunbarton': 'Merrimack',
    'Durham': 'Strafford',
    'East Kingston': 'Rockingham',
    'Easton': 'Grafton',
    'Eaton': 'Carroll',
    'Effingham': 'Carroll',
    'Ellsworth': 'Grafton',
    'Enfield': 'Grafton',
    'Epping': 'Rockingham',
    'Epsom': 'Merrimack',
    'Errol': 'Coos',
    "Erving's Location": 'Coos',
    'Exeter': 'Rockingham',
    'Farmington': 'Strafford',
    'Fitzwilliam': 'Cheshire',
    'Francestown': 'Hillsborough',
    'Franconia': 'Grafton',
    'Franklin': 'Merrimack',
    'Freedom': 'Carroll',
    'Fremont': 'Rockingham',
    'Gilford': 'Belknap',
    'Gilmanton': 'Belknap',
    'Gilsum': 'Cheshire',
    'Goffstown': 'Hillsborough',
    'Gorham': 'Coos',
    'Goshen': 'Sullivan',
    'Grafton': 'Grafton',
    'Grantham': 'Sullivan',
    "Green's Grant": 'Coos',
    'Greenfield': 'Hillsborough',
    'Greenland': 'Rockingham',
    'Greenville': 'Hillsborough',
    'Groton': 'Grafton',
    "Hadley's Purchase": 'Coos',
    "Hale's Location": 'Carroll',
    'Hampstead': 'Rockingham',
    'Hampton': 'Rockingham',
    'Hampton Falls': 'Rockingham',
    'Hancock': 'Hillsborough',
    'Hanover': 'Grafton',
    'Harrisville': 'Cheshire',
    "Hart's Location": 'Carroll',
    'Haverhill': 'Grafton',
    'Hebron': 'Grafton',
    'Henniker': 'Merrimack',
    'Hill': 'Merrimack',
    'Hillsborough': 'Hillsborough',
    'Hinsdale': 'Cheshire',
    'Holderness': 'Grafton',
    'Hollis': 'Hillsborough',
    'Hooksett': 'Merrimack',
    'Hopkinton': 'Merrimack',
    'Hudson': 'Hillsborough',
    'Jackson': 'Carroll',
    'Jaffrey': 'Cheshire',
    'Jefferson': 'Coos',
    'Keene': 'Cheshire',
    'Kensington': 'Rockingham',
    'Kilkenny': 'Coos',
    'Kingston': 'Rockingham',
    'Laconia': 'Belknap',
    'Lancaster': 'Coos',
    'Landaff': 'Grafton',
    'Langdon': 'Sullivan',
    'Lebanon': 'Grafton',
    'Lee': 'Strafford',
    'Lempster': 'Sullivan',
    'Lincoln': 'Grafton',
    'Lisbon': 'Grafton',
    'Litchfield': 'Hillsborough',
    'Littleton': 'Grafton',
    'Livermore': 'Grafton',
    'Londonderry': 'Rockingham',
    'Loudon': 'Merrimack',
    "Low & Burbank's Grant": 'Coos',
    'Lyman': 'Grafton',
    'Lyme': 'Grafton',
    'Lyndeborough': 'Hillsborough',
    'Madbury': 'Strafford',
    'Madison': 'Carroll',
    'Manchester': 'Hillsborough',
    'Marlborough': 'Cheshire',
    'Marlow': 'Cheshire',
    "Martin's Location": 'Coos',
    'Mason': 'Hillsborough',
    'Meredith': 'Belknap',
    'Merrimack': 'Hillsborough',
    'Middleton': 'Strafford',
    'Milan': 'Coos',
    'Milford': 'Hillsborough',
    'Millsfield': 'Coos',
    'Milton': 'Strafford',
    'Monroe': 'Grafton',
    'Mont Vernon': 'Hillsborough',
    'Moultonborough': 'Carroll',
    'Nashua': 'Hillsborough',
    'Nelson': 'Cheshire',
    'New Boston': 'Hillsborough',
    'New Castle': 'Rockingham',
    'New Durham': 'Strafford',
    'New Hampton': 'Belknap',
    'New Ipswich': 'Hillsborough',
    'New London': 'Merrimack',
    'Newbury': 'Merrimack',
    'Newfields': 'Rockingham',
    'Newington': 'Rockingham',
    'Newmarket': 'Rockingham',
    'Newport': 'Sullivan',
    'Newton': 'Rockingham',
    'North Hampton': 'Rockingham',
    'Northfield': 'Merrimack',
    'Northumberland': 'Coos',
    'Northwood': 'Rockingham',
    'Nottingham': 'Rockingham',
    'Odell': 'Coos',
    'Orange': 'Grafton',
    'Orford': 'Grafton',
    'Ossipee': 'Carroll',
    'Pelham': 'Hillsborough',
    'Pembroke': 'Merrimack',
    'Peterborough': 'Hillsborough',
    'Piermont': 'Grafton',
    "Pinkham's Grant": 'Coos',
    'Pittsburg': 'Coos',
    'Pittsfield': 'Merrimack',
    'Plainfield': 'Sullivan',
    'Plaistow': 'Rockingham',
    'Plymouth': 'Grafton',
    'Portsmouth': 'Rockingham',
    'Randolph': 'Coos',
    'Raymond': 'Rockingham',
    'Richmond': 'Cheshire',
    'Rindge': 'Cheshire',
    'Rochester': 'Strafford',
    'Rollinsford': 'Strafford',
    'Roxbury': 'Cheshire',
    'Rumney': 'Grafton',
    'Rye': 'Rockingham',
    'Salem': 'Rockingham',
    'Salisbury': 'Merrimack',
    'Sanbornton': 'Belknap',
    'Sandown': 'Rockingham',
    'Sandwich': 'Carroll',
    "Sargent's Purchase": 'Coos',
    'Seabrook': 'Rockingham',
    'Second College Grant': 'Coos',
    'Sharon': 'Hillsborough',
    'Shelburne': 'Coos',
    'Somersworth': 'Strafford',
    'South Hampton': 'Rockingham',
    'Springfield': 'Sullivan',
    'Stark': 'Coos',
    'Stewartstown': 'Coos',
    'Stoddard': 'Cheshire',
    'Strafford': 'Strafford',
    'Stratford': 'Coos',
    'Stratham': 'Rockingham',
    'Success': 'Coos',
    'Sugar Hill': 'Grafton',
    'Sullivan': 'Cheshire',
    'Sunapee': 'Sullivan',
    'Surry': 'Cheshire',
    'Sutton': 'Merrimack',
    'Swanzey': 'Cheshire',
    'Tamworth': 'Carroll',
    'Temple': 'Hillsborough',
    "Thompson & Meserve's Pur.": 'Coos',
    'Thornton': 'Grafton',
    'Tilton': 'Belknap',
    'Troy': 'Cheshire',
    'Tuftonboro': 'Carroll',
    'Unity': 'Sullivan',
    'Wakefield': 'Carroll',
    'Walpole': 'Cheshire',
    'Warner': 'Merrimack',
    'Warren': 'Grafton',
    'Washington': 'Sullivan',
    'Waterville Valley': 'Grafton',
    'Weare': 'Hillsborough',
    'Webster': 'Merrimack',
    'Wentworth': 'Grafton',
    "Wentworth's Location": 'Coos',
    'Westmoreland': 'Cheshire',
    'Whitefield': 'Coos',
    'Wilmot': 'Merrimack',
    'Wilton': 'Hillsborough',
    'Winchester': 'Cheshire',
    'Windham': 'Rockingham',
    'Windsor': 'Hillsborough',
    'Wolfeboro': 'Carroll',
    'Woodstock': 'Grafton',
}
